title: "Louis Hofer"
description: "Gameplay Programmer"
about: "Gameplay Programmer"
location: "Alpharetta, GA"
email: louisphofer@gmail.com
baseurl: ""

url: "http://louishofer.com" # replace by your site's url
github_username:  punster94
linkedin_username: louis-hofer
linkedin_url: "https://www.linkedin.com/in/louis-hofer-87592a137/"
author: "Louis Hofer"

# google analytics tracking code, please change the value
g_analytics: ""

# add your disqus to enable comments
disqus_shortname:

# language settings
isolang: en
close_btn: "Close"
home_btn: "Home"
projects_btn: "Projects"
posts_btn: "Posts"
imprint_btn: "Contact"
name_badge: "an article by"
rss_badge: "Subscribe"

# build settings
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    tab_width: 4

# third party gems
gems:
  - jekyll-paginate
  - jekyll-gist
  - jemoji

whitelist:
  - jekyll-paginate
  - jekyll-gist
  - jemoji

# exclude files
exclude:
  - LICENSE
  - README.md
